package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Adresse generated by hbm2java
 */
public class Adresse  implements java.io.Serializable {


     private BigDecimal idmembre;
     private Membre membre;
     private String adresse;
     private String ville;
     private String province;
     private String codepostal;

    public Adresse() {
    }

	
    public Adresse(Membre membre) {
        this.membre = membre;
    }
    public Adresse(Membre membre, String adresse, String ville, String province, String codepostal) {
       this.membre = membre;
       this.adresse = adresse;
       this.ville = ville;
       this.province = province;
       this.codepostal = codepostal;
    }
   
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCodepostal() {
        return this.codepostal;
    }
    
    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }




}


