package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client extends Membre implements java.io.Serializable {


     private BigDecimal idmembre;
     private Forfait forfait;
     private Infocredit infocredit;
     private Set locations = new HashSet(0);

    public Client() {
    }

	
    public Client(BigDecimal idmembre, String nomfamille, String prenom, String courriel, String tel, Date datenaissance, String motdepasse, Adresse adresse, Forfait forfait) {
        super(idmembre, nomfamille, prenom, courriel, tel, datenaissance, motdepasse, adresse);
        this.forfait = forfait;
    }
    public Client(BigDecimal idmembre, String nomfamille, String prenom, String courriel, String tel, Date datenaissance, String motdepasse, Adresse adresse, Forfait forfait, Infocredit infocredit, Set locations) {
       super(idmembre, nomfamille, prenom, courriel, tel, datenaissance, motdepasse, adresse);
       this.forfait = forfait;
       this.infocredit = infocredit;
       this.locations = locations;
    }
   @Override
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    @Override
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
   
    public Forfait getForfait() {
        return this.forfait;
    }
    
    public void setForfait(Forfait forfait) {
        this.forfait = forfait;
    }
    public Infocredit getInfocredit() {
        return this.infocredit;
    }
    
    public void setInfocredit(Infocredit infocredit) {
        this.infocredit = infocredit;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }
}


