package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Copie generated by hbm2java
 */
public class Copie  implements java.io.Serializable {


     private BigDecimal numerocopie;
     private Film film;
     private Set locations = new HashSet(0);

    public Copie() {
    }

	
    public Copie(BigDecimal numerocopie, Film film) {
        this.numerocopie = numerocopie;
        this.film = film;
    }
    public Copie(BigDecimal numerocopie, Film film, Set locations) {
       this.numerocopie = numerocopie;
       this.film = film;
       this.locations = locations;
    }
   
    public BigDecimal getNumerocopie() {
        return this.numerocopie;
    }
    
    public void setNumerocopie(BigDecimal numerocopie) {
        this.numerocopie = numerocopie;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


