package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Employe generated by hbm2java
 */
public class Employe extends Membre implements java.io.Serializable {


     private BigDecimal idmembre;
     private Membre membre;
     private Integer matricule;

    public Employe() {
    }

	
    public Employe(Membre membre) {
        this.membre = membre;
    }
    public Employe(BigDecimal idmembre, String nomfamille, String prenom, String courriel, String tel, Date datenaissance, String motdepasse, Adresse adresse, Integer matricule) {
       super(idmembre, nomfamille, prenom, courriel, tel, datenaissance, motdepasse, adresse);
       this.matricule = matricule;
    }
   @Override
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    @Override
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public Integer getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(Integer matricule) {
        this.matricule = matricule;
    }




}


