package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private BigDecimal idmembre;
     private Membre membre;
     private Integer matricule;

    public Employe() {
    }

	
    public Employe(Membre membre) {
        this.membre = membre;
    }
    public Employe(Membre membre, Integer matricule) {
       this.membre = membre;
       this.matricule = matricule;
    }
   
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public Integer getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(Integer matricule) {
        this.matricule = matricule;
    }




}


