package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipetournage generated by hbm2java
 */
public class Equipetournage  implements java.io.Serializable {


     private BigDecimal idpersonne;
     private String nom;
     private Date datenaissance;
     private String lieu;
     private String photo;
     private Blob bio;
     private Set roles = new HashSet(0);
     private Set films = new HashSet(0);

    public Equipetournage() {
    }

	
    public Equipetournage(BigDecimal idpersonne) {
        this.idpersonne = idpersonne;
    }
    public Equipetournage(BigDecimal idpersonne, String nom, Date datenaissance, String lieu, String photo, Blob bio, Set roles, Set films) {
       this.idpersonne = idpersonne;
       this.nom = nom;
       this.datenaissance = datenaissance;
       this.lieu = lieu;
       this.photo = photo;
       this.bio = bio;
       this.roles = roles;
       this.films = films;
    }
   
    public BigDecimal getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(BigDecimal idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getLieu() {
        return this.lieu;
    }
    
    public void setLieu(String lieu) {
        this.lieu = lieu;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Blob getBio() {
        return this.bio;
    }
    
    public void setBio(Blob bio) {
        this.bio = bio;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }
    public Set getFilms() {
        return this.films;
    }
    
    public void setFilms(Set films) {
        this.films = films;
    }




}


