package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait  implements java.io.Serializable {


     private BigDecimal idforfait;
     private String nom;
     private BigDecimal cout;
     private BigDecimal locationmax;
     private BigDecimal dureemax;
     private Set clients = new HashSet(0);

    public Forfait() {
    }

	
    public Forfait(BigDecimal idforfait, BigDecimal cout) {
        this.idforfait = idforfait;
        this.cout = cout;
    }
    public Forfait(BigDecimal idforfait, String nom, BigDecimal cout, BigDecimal locationmax, BigDecimal dureemax, Set clients) {
       this.idforfait = idforfait;
       this.nom = nom;
       this.cout = cout;
       this.locationmax = locationmax;
       this.dureemax = dureemax;
       this.clients = clients;
    }
   
    public BigDecimal getIdforfait() {
        return this.idforfait;
    }
    
    public void setIdforfait(BigDecimal idforfait) {
        this.idforfait = idforfait;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public BigDecimal getCout() {
        return this.cout;
    }
    
    public void setCout(BigDecimal cout) {
        this.cout = cout;
    }
    public BigDecimal getLocationmax() {
        return this.locationmax;
    }
    
    public void setLocationmax(BigDecimal locationmax) {
        this.locationmax = locationmax;
    }
    public BigDecimal getDureemax() {
        return this.dureemax;
    }
    
    public void setDureemax(BigDecimal dureemax) {
        this.dureemax = dureemax;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


