/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locafilm;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Carine
 */
public class FrameRecherche extends javax.swing.JFrame {
    private Controleur c;
    /**
     * Creates new form FrameRecherche
     */
    public FrameRecherche() {
        initComponents();
    }

    public void setC(Controleur c) {
        this.c = c;
    }
    
    public FrameRecherche(Controleur c) {
        initComponents();
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_recherche = new javax.swing.JPanel();
        panel_chercher = new javax.swing.JPanel();
        comboBox_critere = new javax.swing.JComboBox<>();
        bouton_chercher = new javax.swing.JButton();
        textField_critere = new javax.swing.JTextField();
        panel_resultat = new javax.swing.JPanel();
        list_resultat = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bouton_voir_fiche = new javax.swing.JButton();
        bouton_louer = new javax.swing.JButton();
        label_utilisateur = new javax.swing.JLabel();
        label_nom_utilisateur = new javax.swing.JLabel();
        tf_nbLoc = new javax.swing.JTextField();
        label_nbLoc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        comboBox_critere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "titre", "annee", "pays", "langue", "duree", "realisateur", "genre" }));

        bouton_chercher.setText("Chercher");
        bouton_chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_chercherActionPerformed(evt);
            }
        });

        textField_critere.setText("Tapez votre critère");
        textField_critere.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField_critereFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField_critereFocusLost(evt);
            }
        });
        textField_critere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_critereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_chercherLayout = new javax.swing.GroupLayout(panel_chercher);
        panel_chercher.setLayout(panel_chercherLayout);
        panel_chercherLayout.setHorizontalGroup(
            panel_chercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chercherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField_critere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_critere, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bouton_chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_chercherLayout.setVerticalGroup(
            panel_chercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_chercherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_chercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_critere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouton_chercher)
                    .addComponent(textField_critere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(291, 291, 291))
        );

        panel_resultat.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultats"));

        list_resultat.setViewportView(jList1);

        bouton_voir_fiche.setText("voir la fiche");
        bouton_voir_fiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_voir_ficheActionPerformed(evt);
            }
        });

        bouton_louer.setLabel("louer");
        bouton_louer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_louerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_resultatLayout = new javax.swing.GroupLayout(panel_resultat);
        panel_resultat.setLayout(panel_resultatLayout);
        panel_resultatLayout.setHorizontalGroup(
            panel_resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bouton_voir_fiche, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(bouton_louer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_resultatLayout.setVerticalGroup(
            panel_resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_resultatLayout.createSequentialGroup()
                        .addComponent(bouton_voir_fiche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bouton_louer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(list_resultat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap())
        );

        label_utilisateur.setText("Connecté en tant que :");

        tf_nbLoc.setEditable(false);
        tf_nbLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nbLocActionPerformed(evt);
            }
        });

        label_nbLoc.setText("Nb Locations restantes :");

        javax.swing.GroupLayout panel_rechercheLayout = new javax.swing.GroupLayout(panel_recherche);
        panel_recherche.setLayout(panel_rechercheLayout);
        panel_rechercheLayout.setHorizontalGroup(
            panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_resultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_rechercheLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(label_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nom_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_nbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(panel_chercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_rechercheLayout.setVerticalGroup(
            panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(label_nom_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(label_nbLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nbLoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_recherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_louerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_louerActionPerformed
        BigDecimal idFilm = new BigDecimal("1");
        List<Film> listFilm = Facade.getListeFilm();
        String titre = jList1.getSelectedValue();
        
        for(Film f : listFilm)
        {
            if(f.getTitre().equalsIgnoreCase(titre))
                idFilm=f.getIdfilm();
        }
        
        c.louerFilm(idFilm);
    }//GEN-LAST:event_bouton_louerActionPerformed

    private void bouton_chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_chercherActionPerformed
       // System.out.println("Appui");
        String recherche = textField_critere.getText();
        String critere = comboBox_critere.getSelectedItem().toString();
        List<Film> listFilm = Facade.getListeFilm();
        
        DefaultListModel listModel = new DefaultListModel();
        jList1.setModel(listModel);
        
        boolean find = false;


        for (Film f : listFilm) {
            if (critere == "titre") 
            {
                if (f.getTitre().toLowerCase().lastIndexOf(recherche.toLowerCase()) != -1) {find = true;}
                if (find) {
                    listModel.addElement(f.getTitre());
                }
            }
            if (critere == "annee") 
            {
                if (f.getAnnee().toString().equalsIgnoreCase(recherche))
                    listModel.addElement(f.getTitre().toString());
            }
            if (critere == "pays") 
            {
                if (((Pays)f.getPayses().toArray()[0]).getPays().equalsIgnoreCase(recherche))
                    listModel.addElement(f.getTitre());
            }
            if (critere == "langue") 
            {
                if (f.getLangue().toLowerCase().lastIndexOf(recherche.toLowerCase()) != -1) {find = true;}
                if (find) {
                    listModel.addElement(f.getTitre());
                }
            }
            if (critere == "duree") 
            {
                if (f.getDuree().toString().equalsIgnoreCase(recherche))
                    listModel.addElement(f.getTitre().toString());
            }
            if (critere == "realisateur") 
            {
                if (((Equipetournage)f.getRealisateur().toArray()[0]).getNom().toLowerCase().lastIndexOf(recherche.toLowerCase()) != -1) {find = true;}
                if (find) {
                    listModel.addElement(f.getTitre());
                }
            }
            if (critere == "genre") 
            {
                if (((Genre)f.getGenres().toArray()[0]).getGenre().toLowerCase().lastIndexOf(recherche.toLowerCase()) != -1) {find = true;}
                if (find) {
                    listModel.addElement(f.getTitre());
                }
            }
            
            find=false;
        }
    }//GEN-LAST:event_bouton_chercherActionPerformed

    private void bouton_voir_ficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_voir_ficheActionPerformed
        BigDecimal idFilm = new BigDecimal("1");
        List<Film> listFilm = Facade.getListeFilm();
        String titre = jList1.getSelectedValue();
        
        for(Film f : listFilm)
        {
            if(f.getTitre().equalsIgnoreCase(titre))
                idFilm=f.getIdfilm();
        }
        
        c.afficherFilm(idFilm);
    }//GEN-LAST:event_bouton_voir_ficheActionPerformed

    private void textField_critereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_critereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_critereActionPerformed

    private void textField_critereFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField_critereFocusGained
        if(textField_critere.getText().equals("Tapez votre critère")){
            textField_critere.setText("");
        }
    }//GEN-LAST:event_textField_critereFocusGained

    private void textField_critereFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField_critereFocusLost

    }//GEN-LAST:event_textField_critereFocusLost

    private void tf_nbLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nbLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nbLocActionPerformed

    public JLabel getLabel_nom_utilisateur() {
        return label_nom_utilisateur;
    }

    public JLabel getLabel_utilisateur() {
        return label_utilisateur;
    }

    public JTextField getTf_nbLoc() {
        return tf_nbLoc;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRecherche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_chercher;
    private javax.swing.JButton bouton_louer;
    private javax.swing.JButton bouton_voir_fiche;
    private javax.swing.JComboBox<String> comboBox_critere;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel label_nbLoc;
    private javax.swing.JLabel label_nom_utilisateur;
    private javax.swing.JLabel label_utilisateur;
    private javax.swing.JScrollPane list_resultat;
    private javax.swing.JPanel panel_chercher;
    private javax.swing.JPanel panel_recherche;
    private javax.swing.JPanel panel_resultat;
    private javax.swing.JTextField textField_critere;
    private javax.swing.JTextField tf_nbLoc;
    // End of variables declaration//GEN-END:variables
}
