package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Infocredit generated by hbm2java
 */
public class Infocredit  implements java.io.Serializable {


     private BigDecimal idmembre;
     private Client client;
     private String carte;
     private String no;
     private BigDecimal expmois;
     private BigDecimal expannee;
     private BigDecimal cvv;

    public Infocredit() {
    }

	
    public Infocredit(Client client) {
        this.client = client;
    }
    public Infocredit(Client client, String carte, String no, BigDecimal expmois, BigDecimal expannee, BigDecimal cvv) {
       this.client = client;
       this.carte = carte;
       this.no = no;
       this.expmois = expmois;
       this.expannee = expannee;
       this.cvv = cvv;
    }
   
    public BigDecimal getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(BigDecimal idmembre) {
        this.idmembre = idmembre;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getCarte() {
        return this.carte;
    }
    
    public void setCarte(String carte) {
        this.carte = carte;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public BigDecimal getExpmois() {
        return this.expmois;
    }
    
    public void setExpmois(BigDecimal expmois) {
        this.expmois = expmois;
    }
    public BigDecimal getExpannee() {
        return this.expannee;
    }
    
    public void setExpannee(BigDecimal expannee) {
        this.expannee = expannee;
    }
    public BigDecimal getCvv() {
        return this.cvv;
    }
    
    public void setCvv(BigDecimal cvv) {
        this.cvv = cvv;
    }




}


