package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private BigDecimal idlocation;
     private Client client;
     private Copie copie;
     private Date datelocation;
     private Date dateretour;

    public Location() {
    }

	
    public Location(BigDecimal idlocation, Client client, Copie copie) {
        this.idlocation = idlocation;
        this.client = client;
        this.copie = copie;
    }
    public Location(BigDecimal idlocation, Client client, Copie copie, Date datelocation, Date dateretour) {
       this.idlocation = idlocation;
       this.client = client;
       this.copie = copie;
       this.datelocation = datelocation;
       this.dateretour = dateretour;
    }
   
    public BigDecimal getIdlocation() {
        return this.idlocation;
    }
    
    public void setIdlocation(BigDecimal idlocation) {
        this.idlocation = idlocation;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Copie getCopie() {
        return this.copie;
    }
    
    public void setCopie(Copie copie) {
        this.copie = copie;
    }
    public Date getDatelocation() {
        return this.datelocation;
    }
    
    public void setDatelocation(Date datelocation) {
        this.datelocation = datelocation;
    }
    public Date getDateretour() {
        return this.dateretour;
    }
    
    public void setDateretour(Date dateretour) {
        this.dateretour = dateretour;
    }




}


