/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locafilm;

import javafx.scene.paint.Color;
import javax.swing.*;

/**
 *
 * @author PLK
 */
public class LoginWindow extends javax.swing.JFrame {
    private Controleur c;

    public void setC(Controleur c) {
        this.c = c;
    }
    /**
     * Creates new form NewJFrame
     */
    public LoginWindow() {
        initComponents();
    }
    public LoginWindow(Controleur c) {
        initComponents();
        this.setC(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_connexion = new javax.swing.JPanel();
        panel_identifiant = new javax.swing.JPanel();
        label_identifiant = new javax.swing.JLabel();
        tf_identifiant = new javax.swing.JTextField();
        panel_password = new javax.swing.JPanel();
        tf_password = new javax.swing.JPasswordField();
        label_password = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_connexion.setBorder(javax.swing.BorderFactory.createTitledBorder("Connexion"));

        label_identifiant.setText("Login");

        tf_identifiant.setForeground(java.awt.Color.gray);
        tf_identifiant.setText("Courriel / Matricule");
        tf_identifiant.setToolTipText("");
        tf_identifiant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_identifiant.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tf_identifiant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_identifiantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_identifiantFocusLost(evt);
            }
        });
        tf_identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_identifiantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_identifiantLayout = new javax.swing.GroupLayout(panel_identifiant);
        panel_identifiant.setLayout(panel_identifiantLayout);
        panel_identifiantLayout.setHorizontalGroup(
            panel_identifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_identifiant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_identifiantLayout.setVerticalGroup(
            panel_identifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_identifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_identifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_identifiant)
                    .addComponent(tf_identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_connexion.add(panel_identifiant);

        tf_password.setText("12346");
        tf_password.setToolTipText("");
        tf_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_passwordFocusGained(evt);
            }
        });
        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });

        label_password.setText("Mot de passe");

        javax.swing.GroupLayout panel_passwordLayout = new javax.swing.GroupLayout(panel_password);
        panel_password.setLayout(panel_passwordLayout);
        panel_passwordLayout.setHorizontalGroup(
            panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_passwordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_password)
                .addGap(139, 139, 139))
            .addGroup(panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_passwordLayout.createSequentialGroup()
                    .addContainerGap(86, Short.MAX_VALUE)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panel_passwordLayout.setVerticalGroup(
            panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_password)
                .addContainerGap())
            .addGroup(panel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_passwordLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_connexion.add(panel_password);

        jButton1.setText("Connexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_connexion.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_connexion, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTf_identifiant() {
        return tf_identifiant;
    }

    public JTextField getTf_password() {
        return tf_password;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c.connexion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_identifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_identifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_identifiantActionPerformed

    private void tf_identifiantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_identifiantFocusGained
        if (tf_identifiant.getText().equals("Courriel / Matricule")) {
            tf_identifiant.setText("");
            tf_identifiant.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_tf_identifiantFocusGained

    private void tf_identifiantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_identifiantFocusLost
        if(tf_identifiant.getText().isEmpty()){
            tf_identifiant.setForeground(java.awt.Color.gray);
            tf_identifiant.setText("Courriel / Matricule");
        }
    }//GEN-LAST:event_tf_identifiantFocusLost

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void tf_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_passwordFocusGained
        tf_password.setText("");
    }//GEN-LAST:event_tf_passwordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label_identifiant;
    private javax.swing.JLabel label_password;
    private javax.swing.JPanel panel_connexion;
    private javax.swing.JPanel panel_identifiant;
    private javax.swing.JPanel panel_password;
    private javax.swing.JTextField tf_identifiant;
    private javax.swing.JPasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
