package locafilm;
// Generated 18 nov. 2016 16:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays  implements java.io.Serializable {


     private BigDecimal idpays;
     private String pays;
     private Set films = new HashSet(0);

    public Pays() {
    }

	
    public Pays(BigDecimal idpays) {
        this.idpays = idpays;
    }
    public Pays(BigDecimal idpays, String pays, Set films) {
       this.idpays = idpays;
       this.pays = pays;
       this.films = films;
    }
   
    public BigDecimal getIdpays() {
        return this.idpays;
    }
    
    public void setIdpays(BigDecimal idpays) {
        this.idpays = idpays;
    }
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }
    public Set getFilms() {
        return this.films;
    }
    
    public void setFilms(Set films) {
        this.films = films;
    }




}


